version: '3'
services:
  maven:
    image: maven:3-jdk-8
    container_name: calculadora-financeira-maven
    volumes:
      - "./:/etc/projeto"
      - "$HOME/.m2:/root/.m2"
    working_dir: /etc/projeto
    command: ["mvn", "clean", "install"]